version: "3.9"
services:
  appointment-service:
    build: .
    ports: ["4002:4002"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4002
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./:/app
      - /app/node_modules
    profiles: ["standalone"]